openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://localhost:5000
    description: Optional server description, e.g. Main (production) server
paths:
  /hello:
      get:
        summary: Says "Hello!"
        description: Says hello.
        responses:
          '200':    # status code
            description: Hello
            content:
              application/text:
                schema: 
                  type: string
                  